repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # - repo: https://github.com/luarocks/luacheck
  #   rev: v1.1.2
  #   hooks:
  #     - id: luacheck
  #       files: \.lua$
